version: '3.9'
services:
  # PostgreSQL (HotelService DB)
  postgres:
    image: postgres
    container_name: hotelservice-postgres
    restart: always
    environment:
      POSTGRES_USER: poisondev
      POSTGRES_PASSWORD: poisondevdocker
      POSTGRES_DB: neredekalHotelDb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.16.2
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"

  # Logstash (Log verilerini almak ve Elasticsearch'e iletmek)
  logstash:
    image: docker.elastic.co/logstash/logstash:8.16.2
    container_name: logstash
    volumes:
      - ./logstash:/usr/share/logstash/pipeline
      - ./hotelservice/logs:/var/log/hotelservice
      - ./reportservice/logs:/var/log/reportservice
    ports:
      - "5044:5044"  
      - "9600:9600" 
    depends_on:
      - elasticsearch

  # Kibana (Veri görselleştirme ve analiz)
  kibana:
    image: docker.elastic.co/kibana/kibana:8.16.2
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch

networks:
  hotelreport_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
